const V=document.querySelector('#view');let rot=0,tilt=0,mode='command',layers=true,drag=false,lastX=0,lastY=0;
const nav=()=>document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>show(b.dataset.page));
const page=(t,s,b)=>'<div class="page"><div class="eyebrow">GEMCORE • PRE-ACTIVE</div><h1>'+t+'</h1><p class="muted">'+s+'</p>'+b+'</div>';
const tiles=a=>'<div class="grid">'+a.map(x=>'<div class="tile"><h3>'+x+'</h3><p class="muted">GemCore module</p></div>').join('')+'</div>';
const pages={
 command:()=>page('Command Center','Collect • Grade • Trade • Preserve • Belong',tiles(['Start a Submission','Quantum Inspection','Evidence Passport','Live Grading','Human QC','Population Report','Market Intelligence','GemCore Vault'])),
 grade:lab,
 intake:()=>page('Submit a Collectible','Create and track a new grading intake','<div class="tile form"><label>Collectible name<input id="item" placeholder="e.g. 1999 trading card"></label><button class="primary" id="create">Create Submission</button><pre id="out"></pre></div>'),
 passport:passport,
 vault:()=>page('GemCore Vault','Your certified and in-review collection',tiles(['Certified','In Review','Returned Ungraded','Regrade Queue'])),
 market:()=>page('Market Intelligence','Market value is displayed separately and never changes condition grade',tiles(['Comparable Sales','Price History','Market Trend','Set Analytics'])),
 live:()=>page('Live Grading','Capture → VisionCore → Reviewer → Slab QA',tiles(['Capture Feed','VisionCore Events','Reviewer Queue','Slab QA'])),
 settings:()=>page('Settings & Calibration','Hardware, optics, lighting and rubric configuration',tiles(['Digital Microscope','Macro / Telescope Camera','Raking Light','UV / IR','Calibration Health','Rubric Version'])),
 submissions:passport,
 population:()=>page('Population Report','Population by grade, chronology and rank',tiles(['Population by Grade','Chronology','Rank','Regrade History'])),
 qc:()=>page('Human QC','A certified grade cannot be sealed without verified evidence and reviewer approval',tiles(['Review Queue','Evidence Conflicts','Authenticity Gate','Final Seal']))
};
function lab(){
 const checks=['Surface Scan','Edge Analysis','Corner Check','Centering','Print Quality','UV / IR Analysis','Authenticity Check'];
 return page('Grading Lab','AI precision analysis with human verification',
 '<div class="modebar"><button id="collectorMode">Collector</button><button id="commandMode" class="primary">Command</button><button id="layers">Evidence Layers: ON</button><span id="stageState">STAGE 1 • INTAKE</span></div><div class="mockgrid"><div class="scanpanel panel"><h3>AI SCAN IN PROGRESS</h3>'+checks.map(x=>'<div class="scanrow"><span class="tick">✓</span><span>'+x+'<small>Pending</small></span></div>').join('')+'<div class="progress"><i id="progress"></i></div><p class="quote">“EVERY DETAIL MATTERS”</p></div>'+
 '<div class="chamber" id="chamber"><div class="scanner" id="scanner"></div><div class="evidenceLayer" id="evidenceLayer"><i style="left:35%;top:31%"></i><i style="right:34%;top:46%"></i><i style="left:42%;bottom:29%"></i></div><div class="halo h1"></div><div class="halo h2"></div><div class="slab" id="slab"><div class="label"><span>GEMCORE<br><small>INSPECTION</small></span><b id="g">—</b></div><div class="cardface">COLLECTIBLE<br><small>DIGITAL INSPECTION TWIN</small></div></div><div class="controls"><button id="l">↶ Retake / Rotate</button><button id="r">View 3D Model ↷</button><button class="primary" id="scan">Run Deep Scan</button></div></div>'+
 '<div class="rightstack"><div class="panel assistant"><b>VISIONCORE AI</b><span class="online">Online</span><p>Evidence-first inspection assistant.</p><button id="scan2">Run Deep Scan</button></div><div class="panel"><h3>INSPECTION VIEWS</h3><div class="tabs"><button class="primary">Microscope</button><button>Telescope</button><button>3D Model</button></div><div class="micro">SURFACE DETAIL <b>40×</b></div><div class="thumbs"><i>Corner</i><i>Edge</i><i>Holo</i><i>UV</i></div></div><div class="panel"><h3>GRADE BREAKDOWN</h3>'+['Centering','Corners','Edges','Surface','Print Quality'].map(x=>'<div class="metric"><span>'+x+'</span><b>—</b></div>').join('')+'<div class="final">FINAL GRADE<div class="score" id="score">—</div><small id="state">HUMAN QC REQUIRED</small></div></div></div></div>'+
 '<div class="actionbar"><button>Retake Scan</button><button>View 3D Model</button><button class="seal" disabled>✓ Seal Grade</button><button>Generate Report</button><button>Add to Vault</button><button>Share Results</button></div>'+
 '<div class="intel"><div class="panel"><h3>MARKET INTELLIGENCE</h3><strong>Comparable data</strong><div class="spark">╱╲__╱╲╱╲</div></div><div class="panel"><h3>POPULATION REPORT</h3><div class="donut">POP</div></div><div class="panel"><h3>ESTIMATED VALUE</h3><strong>Connect verified market data</strong><p class="muted">Never affects grade.</p></div><div class="panel"><h3>EVIDENCE PASSPORT</h3><p>Full scan images<br>AI analysis report<br>QC record<br>Ownership history</p></div></div>');
}
async function passport(){const a=await fetch('/api/submissions').then(r=>r.json()).catch(()=>[]);V.innerHTML=page('Evidence Passport','Proof in every detail','<div class="grid">'+(a.length?a.map(x=>'<div class="tile"><b>'+x.id+'</b><p>'+x.status+'</p><p class="muted">Evidence observations: '+x.observations.length+' • QC: '+(x.qc.approved?'Approved':'Required')+'</p></div>').join(''):'<div class="tile">No submissions yet.</div>')+'</div>');nav()}
function bind(){nav();const slab=document.querySelector('#slab');if(slab){const chamber=document.querySelector('#chamber');const draw=()=>slab.style.transform='perspective(900px) rotateY('+rot+'deg) rotateX('+tilt+'deg)';chamber.onpointerdown=e=>{drag=true;lastX=e.clientX;lastY=e.clientY;chamber.setPointerCapture?.(e.pointerId)};chamber.onpointermove=e=>{if(!drag)return;rot+=(e.clientX-lastX)*.35;tilt=Math.max(-18,Math.min(18,tilt-(e.clientY-lastY)*.2));lastX=e.clientX;lastY=e.clientY;draw()};chamber.onpointerup=()=>drag=false;chamber.onpointercancel=()=>drag=false;document.querySelector('#collectorMode').onclick=()=>{mode='collector';document.body.dataset.mode=mode;document.querySelector('#collectorMode').classList.add('primary');document.querySelector('#commandMode').classList.remove('primary')};document.querySelector('#commandMode').onclick=()=>{mode='command';document.body.dataset.mode=mode;document.querySelector('#commandMode').classList.add('primary');document.querySelector('#collectorMode').classList.remove('primary')};document.querySelector('#layers').onclick=e=>{layers=!layers;document.querySelector('#evidenceLayer').style.opacity=layers?1:0;e.target.textContent='Evidence Layers: '+(layers?'ON':'OFF')};document.querySelector('#l').onclick=()=>{rot-=18;draw()};document.querySelector('#r').onclick=()=>{rot+=18;draw()};const run=()=>{document.querySelector('#stageState').textContent='STAGE 2 • SPATIAL SCAN';document.querySelector('#scanner').classList.add('active');document.querySelector('#progress').style.width='100%';document.querySelectorAll('.scanrow small').forEach((x,i)=>setTimeout(()=>x.textContent='Analyzed',i*180));setTimeout(()=>{document.querySelector('#stageState').textContent='STAGE 3 • EVIDENCE REVIEW';document.querySelector('#scanner').classList.remove('active');document.querySelector('#score').textContent='9.8*';document.querySelector('#g').textContent='9.8*';document.querySelector('#state').textContent='DEMO • QC REQUIRED'},1500)};document.querySelector('#scan').onclick=run;document.querySelector('#scan2').onclick=run}const c=document.querySelector('#create');if(c)c.onclick=async()=>{const x=await fetch('/api/submissions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({item:{name:document.querySelector('#item').value||'Collectible'}})}).then(r=>r.json());document.querySelector('#out').textContent=JSON.stringify(x,null,2)}}
function show(k){const f=pages[k]||pages.command,x=f();if(x&&x.then)x.then(()=>bind());else{V.innerHTML=x;bind()}}show('grade');